# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatServerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('chinese_name', models.CharField(blank=True, max_length=50, null=True)),
                ('appimportance', models.CharField(blank=True, max_length=5, null=True)),
                ('appcontainer', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=10, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('svr', models.CharField(blank=True, max_length=255, null=True)),
                ('appcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('appcreatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_server_info',
                'managed': False,
            },
        ),
    ]
