# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JmeterRuntime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(blank=True, max_length=100, null=True)),
                ('threads', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('body_data', models.CharField(blank=True, max_length=255, null=True)),
                ('change_lasttime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jmeter_runtime',
                'managed': False,
            },
        ),
    ]
