# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0003_auto_20180613_1351'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jmeterruntime',
            table=None,
        ),
    ]
